# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rewoal
tagline:          'Copy'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a>  Made by <a href="https://facebook.com/temon.temka" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Temuulen'
  url:            https://facebook.com/temon.temka

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rewoal
